### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by chrisnonfer** [ptone/pyosc#12]
After running `pip install pyOSC` or `./setup.py install` on ubuntu 16.04 and mint 18.2 we get the following error preventing installation. 

```
Collecting pyOSC
  Downloading https://files.pythonhosted.org/packages/7c/e4/6abb118cf110813a7922119ed0d53e5fe51c570296785ec2a39f37606d85/pyOSC-0.3.5b-5294.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g9knkxpt/pyOSC/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g9knkxpt/pyOSC/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-g9knkxpt/pyOSC/pip-egg-info
         cwd: /tmp/pip-install-g9knkxpt/pyOSC/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g9knkxpt/pyOSC/setup.py", line 5, in <module>
        import OSC
      File "/tmp/pip-install-g9knkxpt/pyOSC/OSC.py", line 735
        binary = struct.pack('>ll', 0L, 1L)
                                     ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by suyashcjoshi** [comment]
+1 - seeing the same error, any update?

**Comment by flolu** [comment]
Same error. Any ideas on how to fix this?

**Comment by zealtv** [comment]
Solution:
```
pip install pyOSC3
```
